# This is a basic workflow to help you get started with Actions

name: macOS-12 Rooted Emulator w/ SKIA Rendering Test 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: macos-12
  
    steps: 
       - name: install recorder and record session
         run: |
          brew install ffmpeg
          ffmpeg -f avfoundation -i 0 -t 240 out.mov &

       - name: Create Android emulator
         timeout-minutes: 5
         run: |
          #brew install intel-haxm
          # Install AVD files
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;default;x86_64'
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          
          # Create emulator
          $ANDROID_HOME/tools/bin/avdmanager create avd -n TestAvd123 -d pixel --package 'system-images;android-27;default;x86_64'
          $ANDROID_HOME/emulator/emulator -list-avds
          if false; then
          emulator_config=~/.android/avd/TestAvd123.avd/config.ini
          # The following madness is to support empty OR populated config.ini files,
          # the state of which is dependant on the version of the emulator used (which we don't control),
          # so let's be defensive to be safe.
          # Replace existing config (NOTE we're on MacOS so sed works differently!)
          sed -i .bak 's/hw.lcd.density=.*/hw.lcd.density=420/' "$emulator_config"
          sed -i .bak 's/hw.lcd.height=.*/hw.lcd.height=1920/' "$emulator_config"
          sed -i .bak 's/hw.lcd.width=.*/hw.lcd.width=1080/' "$emulator_config"
          # Or, add new config
          if ! grep -q "hw.lcd.density" "$emulator_config"; then
            echo "hw.lcd.density=420" >> "$emulator_config"
          fi
          if ! grep -q "hw.lcd.height" "$emulator_config"; then
            echo "hw.lcd.height=1920" >> "$emulator_config"
          fi
          if ! grep -q "hw.lcd.width" "$emulator_config"; then
            echo "hw.lcd.width=1080" >> "$emulator_config"
          fi
          echo "Emulator settings ($emulator_config)"
          cat "$emulator_config"
          fi
          
       - name: Start Android emulator
         timeout-minutes: 5
         run: |
          echo "Starting emulator and waiting for boot to complete...."
          ls -al $ANDROID_HOME/emulator
          nohup $ANDROID_HOME/tools/emulator -avd TestAvd123 -gpu host -no-audio -no-boot-anim -camera-back none -camera-front none -qemu -m 2048 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do echo "wait..."; sleep 1; done; input keyevent 82'
          echo "Emulator has finished booting"
          $ANDROID_HOME/platform-tools/adb devices

          "$ANDROID_HOME"/platform-tools/adb root
          "$ANDROID_HOME"/platform-tools/adb shell 'su;setprop debug.hwui.renderer skiagl;stop;start'

          sleep 5
          screencapture screenshot.jpg
          $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png

          cat ~/.android/avd/TestAvd123.avd/config.ini > ${{ github.workspace }}/avd-settings.txt || true

       - name: upload video
         uses: actions/upload-artifact@master
         with:
          name: out
          path: out.mov
          
       - uses: actions/upload-artifact@v3
         with:
          name: screenshot.jpg
          path: screenshot.jpg
          
       - uses: actions/upload-artifact@v3
         with:
          name: emulator.png
          path: emulator.png
        
       - uses: actions/upload-artifact@v3
         with:
          name: haxm-checks
          path: |
            ${{ github.workspace }}/**.txt